[theme]
base = "dark"
primaryColor = "#00BFFF"               # bleu clair
backgroundColor = "#0E1117"            # fond très foncé
secondaryBackgroundColor = "#262730"   # fond de cartes plus clair
textColor = "#FAFAFA"                  # texte blanc cassé
font = "sans serif"
